server:
  port: 8080
  servlet:
    context-path: /mig
#dev
#url: jdbc:mysql://172.31.235.64:3306/basic_data?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&autoReconnect=true
#product
#url: jdbc:mysql://172.31.235.102:3306/basic_data?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&autoReconnect=true
spring:
  datasource:
    url: jdbc:mysql://172.31.235.102:3306/basic_data?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: bme
    password: Bme@709394
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.bme.syx.cloud,*
  global-config:
    id-type: 2
    field-strategy: 0
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#debug: true
opentsdb:
  config:
    host: http://172.31.235.89
    port: 4242
    httpConnectionPool: 100
    httpConnectTimeout: 100
    putConsumerThreadCount: 2
    batchPutSize: 20000
    batchPutBufferSize: 50
    batchPutTimeLimit: 300
    readonly: true


